spring:
  datasource:
    url: jdbc:mysql://pranaydb.cwlfnbaf4b8j.us-east-1.rds.amazonaws.com:3306/PranayDB
    username: dutta
    password:  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
        enabled: false

server:
  port: 9091


#PranayDB



